location ~ ^/receive/healthcheck/(live|ready)/ {
    proxy_connect_timeout ${NGINX_RECEIVE_HEALTHCHECK_CONNECT_TIMEOUT_MS}ms;
    proxy_read_timeout ${NGINX_RECEIVE_HEALTHCHECK_READ_TIMEOUT_MS}ms;

    proxy_pass http://receive-service:3000/;
}

location /receive/v1/notifications/batch/ {
    limit_req zone=perip burst=${NGINX_RECEIVE_NOTIFICATIONS_BATCH_RATE_LIMIT} nodelay;

    proxy_connect_timeout ${NGINX_RECEIVE_NOTIFICATIONS_BATCH_CONNECT_TIMEOUT_MS}ms;
    proxy_read_timeout ${NGINX_RECEIVE_NOTIFICATIONS_BATCH_READ_TIMEOUT_MS}ms;

    proxy_pass http://receive-service:3000/notifications/batch/;
}

location /receive/ {
    limit_req zone=perip burst=${NGINX_RECEIVE_RATE_LIMIT} nodelay;
    
    proxy_connect_timeout ${NGINX_RECEIVE_CONNECT_TIMEOUT_MS}ms;
    proxy_read_timeout ${NGINX_RECEIVE_READ_TIMEOUT_MS}ms;

    proxy_pass http://receive-service:3000/;
}

location / {
    return 404;
}